# Generated by Django 3.2.9 on 2021-11-25 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0002_auto_20211125_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(related_name='newsletters', to='newsletters.Tag'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='votes',
            field=models.ManyToManyField(related_name='newsletters_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
