# Generated by Django 3.2.9 on 2021-11-25 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_alter_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 2, 43, 50, 9477)),
        ),
    ]
