# Generated by Django 3.2.9 on 2021-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_alter_tag_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
