# Generated by Django 3.2.9 on 2021-11-25 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0009_auto_20211125_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='newsletters_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
