# Generated by Django 3.2.9 on 2021-11-25 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0010_alter_newsletter_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_at', models.DateField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber', to='newsletters.newsletter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
