# Generated by Django 3.2.9 on 2021-11-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0012_auto_20211125_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
