# Generated by Django 3.2.9 on 2021-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0013_alter_newsletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'DAILY'), (7, 'WEEKLY'), (30, 'MONTHLY')], default=7),
        ),
    ]
